#!/usr/bin/fish

cd ~/myfarms
set -l cept ./vendor/bin/codecept

if test (count $argv) -gt 0
    switch $argv[1]
        case "gen"
            set -l suite $argv[2]
            set -l test $argv[3]
            eval $cept generate:cept $suite $test"Cept"
            subl3 "~/myfarms/myfarms/core/cepts/"$suite"/"$test"Cept.php"
        case "run"
            switch (count $argv)
                case 3
                    time -f "%E" $cept run "--debug" $argv[2] $argv[3]"Cept.php"
                case 2
                    time -f "%E" $cept run $argv[2]
            end
        case "*"
            eval $cept $argv
    end
else
    eval $cept $argv
end
