#!/bin/bash

# Update remotes
git fetch

# Get all branches merged into master
git branch --merged origin/master |
# Exclude current branch
grep -v "^\*" |
# Exclude master
grep -v "^  master\$" |
# Exclude release
grep -v "^  release\$" |
# Delete branches
xargs -n 1 git branch -d 2>/dev/null || echo 'No branches to clean'
