#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Must pass date as arg"
    exit
fi

cat /var/log/pacman.log | grep $1 -a | grep -a "upgraded" | awk '{ printf "%s-%s\n", $5, $6 }' | sed s/\(// | awk '{ printf "/var/cache/pacman/pkg/%s-*.pkg.tar.xz\n", $1 }' | xargs -i sh -c 'echo {}' | xargs -i sh -c 'yes | sudo pacman --noconfirm -U {}'
