#!/usr/bin/fish

set alias $argv[1]
set cmd $argv[2..-1]
echo "Setting $alias to $cmd"
eval "function $alias
    $cmd \$argv
end"
funcsave $alias
#echo "alias $alias=$cmd" >> $HOME/.config/fish/config.fish
