#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Pass filename"
else
    file=$HOME/bin/$1
    if [ -f $file ]; then
        $EDITOR $file
    else
        echo -ne "#!/bin/bash\n\n\n" > $file
        vim $file
        chmod +x $file
    fi
fi
