#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Pass filename, entry class, and input files"
elif [ $# -eq 1 ]; then
    echo "Pass entry class and input files"
elif [ $# -eq 2 ]; then
    echo "Pass input files"
else
    jar cvfe $@
fi
