#!/usr/bin/env python

########################################################################
#                                                                      #
# Copy files using regular expressions.                                #
#                                                                      #
# Examples:                                                            #
#     regcp "SaveQualitySamples(.*)\.php" "SaveToxinSamples\\1.php"    #
#     regcp "(.*)Quality(.*)Controller" "\\1Toxin\\2Controller.coffee" #
#                                                                      #
########################################################################

import os, re, shutil, sys
import argparse
parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description="""
Copy files using regular expressions.
""", epilog="""
Examples:
    regcp "SaveQualitySamples(.*)\.php" "SaveToxinSamples\\1.php"
    regcp "(.*)Quality(.*)Controller" "\\1Toxin\\2Controller.coffee"
""")
parser.add_argument('match', help="the regex to match")
parser.add_argument('to', help="the string to copy to")
parser.add_argument('-d', '--dry', action="store_true", help="dry run")
args = parser.parse_args()


p = re.compile(args.match)

# Get all files in current dir
files = os.listdir('.')
filesToCopy = []
destinations = []

# Match files against regex
print('Copying files:')
for f in files:
    matches = p.search(f)
    if matches:
        print(f)
        filesToCopy.append(f)

# If none found, exit
if len(filesToCopy) is 0:
    print('Files not found')
    sys.exit()

# Generate the destination file names
print('\nTo:')
for f in filesToCopy:
    m=p.search(f)
    dest = p.sub(args.to, f)
    print(dest)
    destinations.append(dest)

# If not a dry run, copy the files
if not args.dry:
    for i in range(len(filesToCopy)):
        shutil.copyfile(filesToCopy[i], destinations[i])
