#!/usr/bin/env python

import os, re, shutil, sys
import argparse
parser = argparse.ArgumentParser(epilog='example: regcp "SaveQualitySamples(.*)\.php" "SaveToxinSamples\\1.php"')
parser.add_argument('match', help="the regex to match")
parser.add_argument('to', help="the string to copy to")
parser.add_argument('-d', '--dry', action="store_true", help="dry run")
args = parser.parse_args()


p = re.compile(args.match)

files = os.listdir('.')
filesToCopy = []
destinations = []
print('Copying files:')
for f in files:
    matches = p.search(f)
    if matches:
        print(f)
        filesToCopy.append(f)

if len(filesToCopy) is 0:
    print('Files not found')
    sys.exit()

print('\nTo:')
for f in filesToCopy:
    m=p.search(f)
    dest = p.sub(args.to, f)
    print(dest)
    destinations.append(dest)

if not args.dry:
    for i in range(len(filesToCopy)):
        shutil.copyfile(filesToCopy[i], destinations[i])
