#!/bin/bash

echo "Adding ssh key: $1"
echo "cat ~/.ssh/server_keys/$1.password" > /tmp/auto-add-key
chmod +x /tmp/auto-add-key
DISPLAY=1 SSH_ASKPASS='/tmp/auto-add-key' ssh-add ~/.ssh/server_keys/$1 < /dev/null
rm /tmp/auto-add-key
